### ISSUE TITLE
Can I change the wrapper element? 

### ISSUE THREAD

**Issue by jktravis** [sniphpet/react-contexify#1]
Hi.

I'm trying to use this in a table where the entire `<tr>` would be the right-click target. The problem is that a `<div>` is not allowed as a child to a `<tbody>`. 

Is there an easy way to change the wrapper for the `menuProvider`, or better still, not use one?

**Comment by sniphpet** [comment]
Hello,

I don't know why I forgot to allow that. Anyway the I need to review the component. 

I'll try to use Children.only instead of a wrapper.
If it doesn't work I'll add the possibility to set the wrapper tag.

I can make a release tonight if you want. 

What do you think ?

**Comment by jktravis** [comment]
Sounds great! Thanks for the quick response!

**Comment by sniphpet** [comment]
Hello,

I made a new release ! I extended the api. You can check the README for more details.
