### ISSUE TITLE
add documentation for Use the Left Click to open menu

### ISSUE THREAD

**Issue by KARTIK01** [sniphpet/react-contexify#2]
Please add code or in documentation explain how can **Use the Left Click** to open menu.

Code given only opens menu on right clicks only.

**Comment by sniphpet** [comment]
Hello,

Actually this is already specified into the documentation : 
![image](https://cloud.githubusercontent.com/assets/5574267/20640300/0d49f236-b3da-11e6-88c9-5e2a18663c18.png)

You can pass an event props  to ```ContextMenuProvider ```, the values are the same as react event :
```
<ContextMenuProvider id="menu_id" event="onClick">
            <YourComponent />
</ContextMenuProvider>;
```

So in your case, if you want to show the menu on left click, pass "onClick" to the event props as  I did above.

**Comment by charlot567** [comment]
Do you have any example on how to trigger the context menu on left click? @fkhadra
